"""
sync_packages.py
────────────────
Compares live KESARi API data against the local packages.js and locale files.
Detects new / changed / removed packages and updates everything automatically:
  1. src/data/packages.js
  2. src/locales/en/tours.json  (pkgNames + itineraries)
  3. src/locales/{lang}/tours.json  for all 12 other languages
"""

import os, json, re, time
from pathlib import Path
from dotenv import load_dotenv
from mistralai.client import Mistral
from kesari_api import fetch_all_packages

load_dotenv()

ROOT       = Path(__file__).parent.parent  # kesari-inbound/
DATA_FILE  = ROOT / "src/data/packages.js"
LOCALE_DIR = ROOT / "src/locales"

LANG_FOLDERS = {
    "es": "es-es", "fr": "fr", "hi": "hi", "de": "de",
    "ja": "ja", "pt": "pt", "it": "it", "zh": "zh",
    "ar": "ar", "ko": "ko", "ml": "ml", "pl": "pl",
}
LANG_NAMES = {
    "es": "Spanish", "fr": "French", "hi": "Hindi", "de": "German",
    "ja": "Japanese", "pt": "Portuguese", "it": "Italian",
    "zh": "Chinese Simplified", "ar": "Arabic",
    "ko": "Korean", "ml": "Malayalam", "pl": "Polish",
}

client = Mistral(api_key=os.environ.get("MISTRAL_API_KEY", ""))


# ── Load existing local packages ───────────────────────────────────────────────

def load_local_packages() -> dict:
    """Parse PACKAGES array from packages.js → dict keyed by code."""
    text = DATA_FILE.read_text(encoding="utf-8")
    # Extract each object between { } inside the PACKAGES array
    pattern = r'\{([^{}]*code:\s*[\'"]([^\'"]+)[\'"][^{}]*)\}'
    result = {}
    for m in re.finditer(pattern, text, re.DOTALL):
        body, code = m.group(1), m.group(2)
        def field(name):
            fm = re.search(rf"{name}:\s*['\"]([^'\"]*)['\"]", body)
            return fm.group(1) if fm else ""
        def int_field(name):
            fm = re.search(rf"{name}:\s*(\d+)", body)
            return int(fm.group(1)) if fm else 0
        result[code] = {
            "code":   code,
            "name":   field("name"),
            "days":   int_field("days"),
            "nights": int_field("nights"),
            "places": field("places"),
            "theme":  field("theme"),
            "tags":   field("tags"),
            "img":    field("img"),
        }
    return result


# ── Diff ───────────────────────────────────────────────────────────────────────

def diff_packages(local: dict, remote: list) -> tuple[list, list, list]:
    """Returns (new_pkgs, changed_pkgs, removed_codes)."""
    remote_map = {p["code"]: p for p in remote}
    new_pkgs, changed_pkgs = [], []

    for pkg in remote:
        code = pkg["code"]
        if code not in local:
            new_pkgs.append(pkg)
        else:
            loc = local[code]
            if (pkg["name"] != loc["name"] or pkg["days"] != loc["days"]
                    or pkg["places"] != loc["places"] or pkg["img"] != loc["img"]):
                changed_pkgs.append(pkg)

    removed = [c for c in local if c not in remote_map]
    return new_pkgs, changed_pkgs, removed


# ── Update packages.js ─────────────────────────────────────────────────────────

def _pkg_js_entry(p: dict) -> str:
    img = p["img"].replace("'", "\\'")
    return (
        f"  {{\n"
        f"    code: '{p['code']}',\n"
        f"    name: '{p['name'].replace(chr(39), chr(92)+chr(39))}',\n"
        f"    days: {p['days']},\n"
        f"    nights: {p['nights']},\n"
        f"    places: '{p['places'].replace(chr(39), chr(92)+chr(39))}',\n"
        f"    theme: '{p['theme']}',\n"
        f"    tags: '{p['tags'].replace(chr(39), chr(92)+chr(39))}',\n"
        f"    img: '{img}',\n"
        f"  }}"
    )


def update_packages_js(remote: list):
    text = DATA_FILE.read_text(encoding="utf-8")
    # Preserve everything after the PACKAGES array (SEASON_DATA, THEME_SLUGS, etc.)
    tail_match = re.search(r'\];\s*\n(export const SEASON_DATA)', text, re.DOTALL)
    tail = f"\n{tail_match.group(1)}" + text.split(tail_match.group(1), 1)[1] if tail_match else ""

    entries = ",\n".join(_pkg_js_entry(p) for p in remote)
    content = (
        "// Auto-generated by sync_packages.py — do not edit manually\n"
        "export const PACKAGES = [\n"
        f"{entries}\n"
        f"];\n{tail}"
    )
    DATA_FILE.write_text(content, encoding="utf-8")
    print(f"  ✔ packages.js updated ({len(remote)} packages)")


# ── Translate helpers ──────────────────────────────────────────────────────────

def translate_name(name: str, lang_name: str) -> str:
    res = client.chat.complete(
        model="mistral-small-latest",
        messages=[{"role": "user", "content":
            f"Translate this India tour package name to {lang_name}. "
            f"Keep place names unchanged. Return ONLY the translated name.\n\"{name}\""}]
    )
    return res.choices[0].message.content.strip().strip('"\'')


def generate_itinerary(pkg: dict) -> dict:
    prompt = (
        f"Create a day-by-day itinerary for this India tour:\n"
        f"Name: {pkg['name']}\nDuration: {pkg['days']} days\nRoute: {pkg['places']}\n\n"
        f"Return ONLY valid JSON:\n"
        f'{{"overview":"...","days":[{{"day":1,"title":"...","desc":"..."}},...]}}\n'
        f"Rules: exactly {pkg['days']} days, day 1 = arrival, last = departure."
    )
    res = client.chat.complete(model="mistral-small-latest",
                               messages=[{"role": "user", "content": prompt}])
    raw = res.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0]
        if raw.startswith("json"): raw = raw[4:]
    parsed = json.loads(raw.strip())
    return {
        "overview": parsed.get("overview", ""),
        "days": [{"day": d["day"], "title": d["title"], "description": d.get("desc", d.get("description", ""))}
                 for d in parsed.get("days", [])]
    }


def translate_itinerary(itin_en: dict, lang_name: str) -> dict:
    days = itin_en["days"]
    inp = {"overview": itin_en["overview"],
           "days": [{"day": d["day"], "title": d["title"], "desc": d["description"]} for d in days]}
    prompt = (
        f"Translate this tour itinerary to {lang_name}. "
        f"Keep geographic proper nouns unchanged. "
        f"Return ONLY valid JSON with same structure (keys: overview, days with day/title/desc).\n\n"
        f"{json.dumps(inp, ensure_ascii=False)}"
    )
    res = client.chat.complete(model="mistral-small-latest",
                               messages=[{"role": "user", "content": prompt}])
    raw = res.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0]
        if raw.startswith("json"): raw = raw[4:]
    parsed = json.loads(raw.strip())
    return {
        "overview": parsed.get("overview", itin_en["overview"]),
        "days": [{"day": d["day"], "title": d.get("title", ""), "description": d.get("desc", d.get("description", ""))}
                 for d in parsed.get("days", [])]
    }


# ── Update locale files ────────────────────────────────────────────────────────

def load_tours_json(folder: str) -> dict:
    path = LOCALE_DIR / folder / "tours.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def save_tours_json(folder: str, data: dict):
    path = LOCALE_DIR / folder / "tours.json"
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def update_locale_for_packages(packages: list):
    """Add pkgNames + itineraries for given packages into all locale files."""
    print(f"\n  Updating locales for {len(packages)} package(s)...")

    for pkg in packages:
        code = pkg["code"]
        name_en = pkg["name"]
        print(f"\n  [{code}] {name_en}")

        # English locale
        en_tours = load_tours_json("en")
        en_tours.setdefault("pkgNames", {})[code] = name_en

        # Generate English itinerary
        print(f"    Generating itinerary...")
        try:
            itin_en = generate_itinerary(pkg)
            en_tours.setdefault("itineraries", {})[code] = itin_en
        except Exception as e:
            print(f"    ✗ itinerary failed: {e}")
            itin_en = None

        save_tours_json("en", en_tours)
        print(f"    ✔ English updated")

        # All other languages
        for lang_code, folder in LANG_FOLDERS.items():
            lang_name = LANG_NAMES[lang_code]
            try:
                time.sleep(2)
                tours = load_tours_json(folder)

                # Translate package name
                translated_name = translate_name(name_en, lang_name)
                tours.setdefault("pkgNames", {})[code] = translated_name

                # Translate itinerary
                if itin_en:
                    time.sleep(2)
                    itin_translated = translate_itinerary(itin_en, lang_name)
                    tours.setdefault("itineraries", {})[code] = itin_translated

                save_tours_json(folder, tours)
                print(f"    ✔ {lang_name}: {translated_name}")
            except Exception as e:
                print(f"    ✗ {lang_name}: {e}")


# ── Main sync ──────────────────────────────────────────────────────────────────

def sync(force_all: bool = False) -> dict:
    """
    Run a full sync. Returns summary dict.
    If force_all=True, updates packages.js and all locales even if nothing changed.
    """
    print("Fetching live data from KESARi API...")
    remote = fetch_all_packages()
    print(f"  {len(remote)} packages fetched")

    print("\nLoading local packages.js...")
    local = load_local_packages()
    print(f"  {len(local)} packages in local file")

    new_pkgs, changed_pkgs, removed = diff_packages(local, remote)

    print(f"\nDiff result:")
    print(f"  New     : {len(new_pkgs)}")
    print(f"  Changed : {len(changed_pkgs)}")
    print(f"  Removed : {len(removed)}")

    if not new_pkgs and not changed_pkgs and not removed and not force_all:
        print("\n✔ Everything is up to date — no changes needed.")
        return {"new": 0, "changed": 0, "removed": 0}

    # Always rewrite packages.js with full remote list
    print("\nUpdating packages.js...")
    update_packages_js(remote)

    # Update locales for new and changed packages
    to_update = new_pkgs + changed_pkgs
    if to_update:
        update_locale_for_packages(to_update)

    if removed:
        print(f"\n⚠ {len(removed)} packages removed from API: {removed}")
        print("  (Not auto-deleted — review manually)")

    print("\n✔ Sync complete!")
    return {"new": len(new_pkgs), "changed": len(changed_pkgs), "removed": len(removed)}


if __name__ == "__main__":
    sync()
